
// Quiz Data
const QuizzData = [
  {
    id: 1,
    title: "Bí ẩn Hoàng Thành Huế",
    description: "Khám phá những điều thú vị về cung đình Huế qua 15 câu hỏi thú vị",
    image: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=400&h=300&fit=crop",
    difficulty: "Cơ bản",
    difficultyColor: "bg-green-500",
    questions: 15,
    time: "10 phút",
    players: "12.5K",
    rating: 4.9,
    category: "Kiến trúc",
    badge: "🏛️",
    isHot: true,
    reward: "Huy hiệu Hoàng Gia",
    completedBy: 8200
  },
  {
    id: 2,
    title: "Truyền thuyết Hồ Gươm",
    description: "Tìm hiểu câu chuyện lịch sử và truyền thuyết xung quanh Hồ Gươm",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
    difficulty: "Trung cấp",
    difficultyColor: "bg-blue-500",
    questions: 20,
    time: "12 phút",
    players: "8.3K",
    rating: 4.8,
    category: "Lịch sử",
    badge: "⚔️",
    isHot: false,
    reward: "Huy hiệu Rùa Thiêng",
    completedBy: 6100
  },
  {
    id: 3,
    title: "54 Dân tộc Việt Nam",
    description: "Khám phá văn hóa đa dạng của 54 dân tộc anh em",
    image: "https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=400&h=300&fit=crop",
    difficulty: "Nâng cao",
    difficultyColor: "bg-purple-500",
    questions: 25,
    time: "15 phút",
    players: "15.2K",
    rating: 4.7,
    category: "Văn hóa",
    badge: "🏔️",
    isHot: true,
    reward: "Huy hiệu Đại Đoàn Kết",
    completedBy: 11800
  },
  {
    id: 4,
    title: "Hội An Phố Cổ",
    description: "Tìm hiểu về kiến trúc và văn hóa độc đáo của phố cổ Hội An",
    image: "https://images.unsplash.com/photo-1517832606299-7ae9b720a186?w=400&h=300&fit=crop",
    difficulty: "Cơ bản",
    difficultyColor: "bg-green-500",
    questions: 18,
    time: "8 phút",
    players: "9.7K",
    rating: 4.6,
    category: "Di sản",
    badge: "🏮",
    isHot: false,
    reward: "Huy hiệu Phố Cổ",
    completedBy: 7400
  },
  {
    id: 5,
    title: "Âm nhạc Cung Đình",
    description: "Khám phá nghệ thuật âm nhạc cung đình Việt Nam",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop",
    difficulty: "Trung cấp",
    difficultyColor: "bg-blue-500",
    questions: 22,
    time: "14 phút",
    players: "6.8K",
    rating: 4.5,
    category: "Nghệ thuật",
    badge: "🎵",
    isHot: true,
    reward: "Huy hiệu Nhạc Sĩ",
    completedBy: 5200
  },
  {
    id: 6,
    title: "Lễ hội Truyền thống",
    description: "Tìm hiểu về các lễ hội truyền thống đặc sắc của Việt Nam",
    image: "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=400&h=300&fit=crop",
    difficulty: "Cơ bản",
    difficultyColor: "bg-green-500",
    questions: 16,
    time: "10 phút",
    players: "11.3K",
    rating: 4.8,
    category: "Lễ hội",
    badge: "🎊",
    isHot: false,
    reward: "Huy hiệu Lễ Hội",
    completedBy: 8900
  }
];

export default QuizzData;